#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          displaylink-driver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: DisplayLink driver
# Description:       Manage DisplayLink driver
### END INIT INFO

# Author: Gabriel Hondet <gabriel.hondet@gmail.com>

DESC="DisplayLink driver"
DAEMON=/opt/displaylink/DisplayLink

do_start () {
    log_daemon_msg "Starting $DESC"
    modprobe evdi || (dkms install evdi && modprobe evdi)
    if [ $? -ne 0 ]; then
        log_failure_msg "Error loading evdi"
        exit 1
    fi
    start_daemon "$DAEMON"
    if [ $? -ne 0 ]; then
        log_failure_msg "Error starting $DAEMON"
        exit 1
    else
        log_success_msg "Started $DAEMON"
    fi
    exit 0
}
